### ISSUE TITLE
Remove constructor creation on sleigh-compile

### ISSUE THREAD

**Issue by rbran** [icicle-emu/icicle-emu#33]
This issue lists the required improvements required to stop ignoring the [constructor creation error](https://github.com/icicle-emu/icicle-emu/blob/75f0259dfb264e3ffd7d2ecd1f9ede3a9a65d9d9/sleigh/sleigh-compile/src/lib.rs#L296-L300):

- [ ] Allow context variables in disassembly_action expressions: https://github.com/icicle-emu/icicle-emu/issues/28
- [ ] Allow subtables to be used in address of operations: https://github.com/icicle-emu/icicle-emu/issues/30
- [ ] Allow pattern values to contain complex expressions: https://github.com/icicle-emu/icicle-emu/issues/31
- [ ] Allow Bitrange: https://github.com/icicle-emu/icicle-emu/issues/32
